name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Menggunakan rentang versi yang lebih fleksibel

dependencies:
  flutter:
    sdk: flutter

  # Your existing packages
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0 # Versi terbaru yang stabil
  percent_indicator: ^4.2.3 # Versi terbaru yang stabil
  path_provider: ^2.1.3
  csv: ^6.0.0
  printing: ^5.12.0
  pdf: ^3.10.8
  mqtt_client: ^10.2.0
  logger: ^2.3.0 # Versi terbaru yang stabil
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Versi terbaru yang stabil

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_pens.png